spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jackson:
    time-zone: Asia/Seoul

  profiles:
    active:
      - local
    group:
      local:
        - oauth
        - db-local
      dev:
        - oauth
        - db-dev
    include: db, oauth

logging:
  level:
    org.springframework.security: DEBUG
    com.victory: DEBUG